pub fn err_handl() {
    panic!("This is err out");
    
}